


PATHS:
      data_donor_imp: '/workspaces/debug/Donor imputation_bank savings_forsc/bank_donor_output_forsc.xlsx'
      data_hist_imp: '/workspaces/debug/data/W3_W4_combined_for_trend_imputation.xlsx'
      output_dir: '/workspaces/debug/Donor imputation_bank savings_forsc/'
      output_file_donor: test_output_donor_bank.xlsx
      output_file_hist_income: test_output_hist_income.xlsx
      output_file_hist_housing: test_output_hist_housing.xlsx


IMPUTATION:

      DONOR_IMPUTATION:
              # 1. Add a new line for every variable that needs to be imputated with donor imputation
              # 2. Format: <variable-name> : <list-of-imputation-class-variables>
              
              #'Q312a1_1_1': ['Q309', 'Q311', 'Q312a1_1_1', 'Q313b_1', 'Q314_1_1', 'Q315_1_1', 'Q312a1_1_2', 'Q313b_2', 'Q314_1_2', 'Q315_1_2', 'Q312a1_1_3', 'Q313b_3', 'Q314_1_3', 'Q315_1_3', 'Q312a1_1_4', 'Q313b_4', 'Q314_1_4', 'Q315_1_4', 'Q312a1_1_5', 'Q313b_5', 'Q314_1_5', 'Q315_1_5', 'Q312a1_1_6', 'Q313b_6', 'Q314_1_6', 'Q315_1_6', 'Q312a1_1_7', 'Q313b_7', 'Q314_1_7', 'Q315_1_7', 'Q312a1_1_8', 'Q313b_8', 'Q314_1_8', 'Q315_1_8', 'Q312a1_1_9', 'Q313b_9', 'Q314_1_9', 'Q315_1_9', 'Q312a1_1_10', 'Q313b_10', 'Q314_1_10', 'Q315_1_10']
              'Q312a1_1_1': ['Q309', 'Q311']